version: 0.2

env:
  variables:
    LambdaBucketName: "kd-freelancing"

phases:
  build:
    commands:
      - |
        for dir in lambdas/*; do
          if [ -d "$dir" ]; then
            folder_name=$(basename "$dir")
            zip -r "$folder_name.zip" "$dir"
            aws s3 cp "$folder_name.zip" s3://$LambdaBucketName/lambdas/"$folder_name.zip"
            rm "$folder_name.zip"
          fi
        done
