AWSTemplateFormatVersion: '2010-09-09'
Description: Setup API Gateway with Lambda integration for POST request

Parameters:
  LambdaBucketName:
    Description: The name of the S3 bucket where the lambda will be stored
    Type: String

  SourceBucketName:
    Description: The name of the S3 bucket for which we will generate the pre-signed URL
    Type: String

  StageName:
    Description: The name of the stage for the API Gateway
    Type: String

Resources:
  PreSignedUrlGeneratorAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: PreSignedUrlGeneratorAPI
      ProtocolType: HTTP

  AccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/PreSignedUrlGeneratorAPI

  PreSignedUrlGeneratorExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PreSignedUrlGeneratorExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: LambdaS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::${SourceBucketName}/*"

  PreSignedUrlGeneratorFunction:
    Type: AWS::Lambda::Function
    DependsOn: PreSignedUrlGeneratorExecutionRole
    Properties:
      FunctionName: PreSignedUrlGeneratorFunction
      Runtime: python3.11
      Handler: lambda.lambda_handler
      Timeout: 30
      Role: !GetAtt PreSignedUrlGeneratorExecutionRole.Arn
      TracingConfig:
        Mode: Active
      Code:
        S3Bucket: !Ref LambdaBucketName
        S3Key: lambdas/presigned-url-function.zip
        S3ObjectVersion: "{{resolve:ssm:LambdaVersion_presigned-url-function}}"

  PreSignedUrlGeneratorFunctionExecutionPolicy:
    Type: AWS::IAM::Policy
    DependsOn: PreSignedUrlGeneratorExecutionRole
    Properties:
      PolicyName: PreSignedUrlGeneratorFunctionExecutionPolicy
      Roles:
        - !Ref PreSignedUrlGeneratorExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"

  APIIntegration:
    Type: AWS::ApiGatewayV2::Integration
    DependsOn: PreSignedUrlGeneratorFunction
    Properties:
      ApiId: !Ref PreSignedUrlGeneratorAPI
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PreSignedUrlGeneratorFunction.Arn}/invocations"
      PayloadFormatVersion: "2.0"

  APIRoute:
    Type: AWS::ApiGatewayV2::Route
    DependsOn: APIIntegration
    Properties:
      ApiId: !Ref PreSignedUrlGeneratorAPI
      RouteKey: 'POST /files'
      Target: !Sub integrations/${APIIntegration}

  APIStage:
    Type: AWS::ApiGatewayV2::Stage
    DependsOn: APIRoute
    Properties:
      StageName: !Ref StageName
      Description: Production Stage
      ApiId: !Ref PreSignedUrlGeneratorAPI
      AutoDeploy: true
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogGroup.Arn
        Format: '{"requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","path":"$context.path","status":"$context.status","requestId":"$context.requestId"}'

  APIDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn: APIStage
    Properties:
      ApiId: !Ref PreSignedUrlGeneratorAPI

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt PreSignedUrlGeneratorFunction.Arn
      Principal: apigateway.amazonaws.com

Outputs:
  ApiUrl:
    Description: URL of the created API
    Value: !Sub "https://${PreSignedUrlGeneratorAPI}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/files/"
