AWSTemplateFormatVersion: '2010-09-09'
Description: Setup API Gateway with Lambda integration for POST request

Resources:
  PreSignedUrlGeneratorAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: PreSignedUrlGeneratorAPI
      ProtocolType: HTTP

  PreSignedUrlGeneratorExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PreSignedUrlGeneratorExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: "arn:aws:s3:::kd-freelancing/*"

  PreSignedUrlGeneratorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: PreSignedUrlGeneratorFunction
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      Role: !GetAtt PreSignedUrlGeneratorExecutionRole.Arn
      Code:
        S3Bucket: kd-freelancing
        S3Key: lambdas/presigned-url-function/lambda.py

  APIIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PreSignedUrlGeneratorAPI
      IntegrationType: HTTP
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PreSignedUrlGeneratorFunction.Arn}/invocations"

  APIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PreSignedUrlGeneratorAPI
      RouteKey: 'POST /files'
      Target: !Sub integrations/${APIIntegration.Id}

Outputs:
  ApiUrl:
    Description: URL of the created API
    Value: !Sub "https://${PreSignedUrlGeneratorAPI.Id}.execute-api.${AWS::Region}.amazonaws.com/files/"
